<?php

/**
 * @file
 * Pop-ups a full-screen navigation
 */

/**
 * Implements hook_block_info().
 */
function popupnav_block_info() {
  $blocks['popupnav'] = array(
    'info' => t('Pop-up Full-Screen Navigation'),
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function popupnav_block_configure($delta = '') {
// This example comes from node.module.
/*
*$form = array();
*if ($delta == 'recent') {
*  $form['node_recent_block_count'] = array(
*    '#type' => 'select',
*    '#title' => t('Number of recent content items to display'),
*    '#default_value' => variable_get('node_recent_block_count', 10),
*    '#options' => drupal_map_assoc(array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 25, 30)),
*  );
*}
*/

$form = array();

if ($delta == 'popupnav') {

$form['popupnav_settings'] = array(
  '#type' => 'fieldset',
  '#title' => t('Pop-up Navigation Settings'),

  'popupnav_settings_menu' => array(
    '#type' => 'select',
    '#title' => t('Select a menu'),
    '#default_value' => variable_get('popupnav_settings_menu'),
    '#options' => menu_get_menus(),
    ),
  'popupnav_settings_title' => array(
    '#type' => 'checkbox',
    '#title' => t('Show block title as Heading'),
    '#default_value' => variable_get('popupnav_settings_title'),
    ),
  'popupnav_settings_trigger' => array(
    '#type' => 'textfield',
    '#title' => t('Menu trigger title'),
    '#default_value' => variable_get('popupnav_settings_trigger', '<i>&#9776;</i> Menu'),
    '#description' => t('You can use an Entypo icon font or HTML. I recommend you to wrap the icon with the html i tag'),
    ),

);
}
return $form;
}

/**
* Implements hook_block_save($delta = '', $edit = array().
*/
function popupnav_block_save($delta = '', $edit = array()) {
// This example comes from node.module.
/*
 *if ($delta == 'recent') {
 *  variable_set('node_recent_block_count', $edit['node_recent_block_count']);
 *}
 */
/* Your code here */
    if ($delta == "popupnav"){
        variable_set('popupnav_settings_menu', $edit['popupnav_settings_menu']);
        variable_set('popupnav_settings_title', $edit['popupnav_settings_title']);
        variable_set('popupnav_settings_trigger', $edit['popupnav_settings_trigger']);
    }
}

/**
 * Implements hook_block_view().
 */
function popupnav_block_view($delta = '') {
  $block = array();

   // get the selected menu data
    $selected_menu = variable_get('popupnav_settings_menu');
    $menu = menu_tree_all_data($selected_menu);

  if($delta == "popupnav"){
    $block['subject'] = NULL;
    $block['content'] = array(
        '#theme' => 'popupnav_theme',
        '#tree' => $menu,
        '#attached' => array(
            'css' => array(drupal_get_path("module", "popupnav") . '/popupnav.css'),
            'js' => array(drupal_get_path("module", "popupnav") . '/popupnav.js'),
        ),
    );
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function popupnav_theme($existing, $type, $theme, $path) {
  return array(
    /*
     *'forum_icon' => array(
     *  'variables' => array('new_posts' => NULL, 'num_posts' => 0, 'comment_mode' => 0, 'sticky' => 0),
     *),
     *'status_report' => array(
     *  'render element' => 'requirements',
     *  'file' => 'system.admin.inc',
     *),
     */
    'popupnav_theme' => array(
        'variables' => array(
            'tree' => array(),
            'attributes' => array(),
        ),
    ),
    );
}

function popupnav_preprocess_block(&$variables, $hook){
   if ($variables['block']->module == 'popupnav') {
    $variables['elements']['#block']->subject = NULL;
  }
}

function theme_popupnav_theme($variables = array()){

    $block = block_load("popupnav", "popupnav");
    $block_title = ($block->title);
    $show_title = variable_get('popupnav_settings_title', FALSE);

    $menu_trigger = variable_get('popupnav_settings_trigger');

    $menu_tree = $variables['tree'];

    $output = '<div id="popupnav-container">';
    $output .= '<div id="popupnav-fullscreen"><div class="popupnav-wrapper">';
    $output .= '<div class="popupnav-close"><a href="#"><i>&#10060;</i>&nbsp;' . t('Close') . '</a></div>';
        if($show_title){
            $output .= '<h2>'.$block_title.'</h2>';
        }
    $output .= '<nav class="popupnav-navigation">';
        $output .= '<ul>';
            foreach ($menu_tree as $link) {
                //dpm($link);
                $output .= '<li class="first-level item-' . $link['link']['mlid'] . '">';
                $output .= l($link['link']['link_title'], $link['link']['link_path'], $link['link']['options']);
                    if(!empty($link['below'])){
                        $output .= '<ul>';
                            foreach ($link['below'] as $second_link) {
                                $output .= '<li class="second-level item-' . $link['link']['mlid'] . '">';
                                $output .= l($second_link['link']['link_title'], $second_link['link']['link_path'], $second_link['link']['options']);
                                $output .= '</li>';
                            }
                        $output .= '</ul>';
                    }
                $output .= '</li>';
            }
        $output .= '</ul>';
    $output .= '</nav>';
    $output .= '</div></div>'; //#popupnav-fullscreen and .popupnav-wrapper
    $output .= '<div class="popupnav-trigger"><a href="#">'.$menu_trigger.'</a></div>';
    $output .= '</div>';
    return $output;
}